package Vistas;


import Entity.Persistencia;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jpaController.EscenarioJpaController;
import jpaController.FestivalJpaController;
import jpaController.PresentacionJpaController;
import jpaController.UsuarioJpaController;
/**
 *
 * @author Jennifer
 */
public class Administrador extends javax.swing.JFrame {
    private Persistencia persis;
    private UsuarioJpaController usuarioController;
    private FestivalJpaController festivalController;
    private EscenarioJpaController escenarioController;
    private PresentacionJpaController presentacionController;
    
    /**
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();
        persis = new Persistencia();
        usuarioController = new UsuarioJpaController(persis.getEmf());
        festivalController = new FestivalJpaController(persis.getEmf());
        escenarioController = new EscenarioJpaController(persis.getEmf());
        presentacionController = new PresentacionJpaController(persis.getEmf());
        
        cargarUsuarios();
        cargarFestivales();
        cargarEscenarios();
        cargarPresentaciones();
    }
    
    private void cargarUsuarios() {
        DefaultTableModel model = (DefaultTableModel) tblUsuarios.getModel();
        model.setRowCount(0);
        
        List<Entity.Usuario> usuarios = usuarioController.findUsuarioEntities();
        for (Entity.Usuario usuario : usuarios) {
            Object[] row = {
                usuario.getIdUsuario(),
                usuario.getNombreU(),
                usuario.getIdRol().getDescripcion()
            };
            model.addRow(row);
        }
    }
    
    private void cargarFestivales() {
        DefaultTableModel model = (DefaultTableModel) tblFestival.getModel();
        model.setRowCount(0);
        
        List<Entity.Festival> festivales = festivalController.findFestivalEntities();
        for (Entity.Festival festival : festivales) {
            Object[] row = {
                festival.getIdFestival(),
                festival.getNombre(),
                festival.getFechaInicio(),
                festival.getFechaFinal()
            };
            model.addRow(row);
        }
    }
    
    private void cargarEscenarios() {
        DefaultTableModel model = (DefaultTableModel) tblEscenarios.getModel();
        model.setRowCount(0);
        
        List<Entity.Escenario> escenarios = escenarioController.findEscenarioEntities();
        for (Entity.Escenario escenario : escenarios) {
            Object[] row = {
                escenario.getIdEscenario(),
                escenario.getNombre(),
                escenario.getCapacidad(),
                escenario.getUbicacion()
            };
            model.addRow(row);
        }
    }
    
    private void cargarPresentaciones() {
        DefaultTableModel model = (DefaultTableModel) tblPresentaciones.getModel();
        model.setRowCount(0);
        
        List<Entity.Presentacion> presentaciones = presentacionController.findPresentacionEntities();
        for (Entity.Presentacion presentacion : presentaciones) {
            Object[] row = {
                presentacion.getIdPresentacion(),
                presentacion.getTitulo(),
                presentacion.getDuracion(),
                presentacion.getCostoBase(),
                presentacion.getIdEscenario().getNombre(),
                presentacion.getIdFestival().getNombre()
            };
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        btnEliminarFestival = new javax.swing.JButton();
        btnAgregarUsuario = new javax.swing.JButton();
        btnAgregarFestival = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        btnAgregarEscenario = new javax.swing.JButton();
        btnEliminarEscenario = new javax.swing.JButton();
        btnAgregarPresentacion = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblFestival = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblEscenarios = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblPresentaciones = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menu.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setText("BIENVENIDO ADMINISTRADOR");

        btnEliminarFestival.setBackground(new java.awt.Color(102, 204, 255));
        btnEliminarFestival.setText("ELIMINAR FESTIVAL");
        btnEliminarFestival.setBorder(null);
        btnEliminarFestival.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarFestival.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarFestivalActionPerformed(evt);
            }
        });

        btnAgregarUsuario.setBackground(new java.awt.Color(102, 204, 255));
        btnAgregarUsuario.setText("AGREGAR USUARIO");
        btnAgregarUsuario.setBorder(null);
        btnAgregarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarUsuarioActionPerformed(evt);
            }
        });

        btnAgregarFestival.setBackground(new java.awt.Color(102, 204, 255));
        btnAgregarFestival.setText("AGREGAR FESTIVAL");
        btnAgregarFestival.setBorder(null);
        btnAgregarFestival.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarFestival.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarFestivalActionPerformed(evt);
            }
        });

        btnCerrarSesion.setBackground(new java.awt.Color(102, 204, 255));
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        btnAgregarEscenario.setBackground(new java.awt.Color(102, 204, 255));
        btnAgregarEscenario.setText("AGREGAR ESCENARIO");
        btnAgregarEscenario.setBorder(null);
        btnAgregarEscenario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarEscenario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEscenarioActionPerformed(evt);
            }
        });

        btnEliminarEscenario.setBackground(new java.awt.Color(102, 204, 255));
        btnEliminarEscenario.setText("ELIMINAR ESCENARIO");
        btnEliminarEscenario.setBorder(null);
        btnEliminarEscenario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarEscenario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEscenarioActionPerformed(evt);
            }
        });

        btnAgregarPresentacion.setBackground(new java.awt.Color(102, 204, 255));
        btnAgregarPresentacion.setText("AGREGAR PRESENTACIÓN");
        btnAgregarPresentacion.setBorder(null);
        btnAgregarPresentacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarPresentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPresentacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(menuLayout.createSequentialGroup()
                                .addComponent(btnAgregarFestival, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEliminarFestival, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                                .addComponent(btnAgregarEscenario, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEliminarEscenario, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnAgregarUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAgregarPresentacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(menuLayout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(menuLayout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(jLabel1))
                            .addGroup(menuLayout.createSequentialGroup()
                                .addGap(162, 162, 162)
                                .addComponent(btnCerrarSesion)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarFestival, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarFestival, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarEscenario, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarEscenario, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAgregarPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Usuario", "Rol"
            }
        ));
        jScrollPane4.setViewportView(tblUsuarios);

        jTabbedPane1.addTab("Usuarios", jScrollPane4);

        tblFestival.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Fecha de Inicio", "Fecha de Fin"
            }
        ));
        jScrollPane5.setViewportView(tblFestival);

        jTabbedPane1.addTab("Festival", jScrollPane5);

        tblEscenarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Capacidad", "Ubicación"
            }
        ));
        jScrollPane6.setViewportView(tblEscenarios);

        jTabbedPane1.addTab("Escenarios", jScrollPane6);

        tblPresentaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Título", "Duración", "Costo base"
            }
        ));
        jScrollPane7.setViewportView(tblPresentaciones);

        jTabbedPane1.addTab("Presentaciones", jScrollPane7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarFestivalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarFestivalActionPerformed
        int filaSeleccionada = tblFestival.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un festival para eliminar");
            return;
        }
        
        int idFestival = (int) tblFestival.getValueAt(filaSeleccionada, 0);
        try {
            festivalController.destroy(idFestival);
            cargarFestivales();
            JOptionPane.showMessageDialog(this, "Festival eliminado correctamente");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar festival: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEliminarFestivalActionPerformed

    private void btnAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarUsuarioActionPerformed
        DialogoUsuarios dialogo = new DialogoUsuarios(this, true, null);
        dialogo.setVisible(true);
        cargarUsuarios();
    }//GEN-LAST:event_btnAgregarUsuarioActionPerformed

    private void btnAgregarFestivalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarFestivalActionPerformed
        DialogoFestival dialogo = new DialogoFestival(this, true, null);
        dialogo.setVisible(true);
        cargarFestivales();
    }//GEN-LAST:event_btnAgregarFestivalActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnAgregarEscenarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEscenarioActionPerformed
        DialogoEscenario dialogo = new DialogoEscenario(this, true, null);
        dialogo.setVisible(true);
        cargarEscenarios();
    }//GEN-LAST:event_btnAgregarEscenarioActionPerformed

    private void btnEliminarEscenarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEscenarioActionPerformed
        int filaSeleccionada = tblEscenarios.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un escenario para eliminar");
            return;
        }
        
        int idEscenario = (int) tblEscenarios.getValueAt(filaSeleccionada, 0);
        try {
            escenarioController.destroy(idEscenario);
            cargarEscenarios();
            JOptionPane.showMessageDialog(this, "Escenario eliminado correctamente");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar escenario: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEliminarEscenarioActionPerformed

    private void btnAgregarPresentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPresentacionActionPerformed
        DialogoPresentacion dialogo = new DialogoPresentacion(this, true, null);
        dialogo.setVisible(true);
        cargarPresentaciones();
    }//GEN-LAST:event_btnAgregarPresentacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarEscenario;
    private javax.swing.JButton btnAgregarFestival;
    private javax.swing.JButton btnAgregarPresentacion;
    private javax.swing.JButton btnAgregarUsuario;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnEliminarEscenario;
    private javax.swing.JButton btnEliminarFestival;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel menu;
    private javax.swing.JTable tblEscenarios;
    private javax.swing.JTable tblFestival;
    private javax.swing.JTable tblPresentaciones;
    private javax.swing.JTable tblUsuarios;
    // End of variables declaration//GEN-END:variables
}
