package Vistas;


import Entity.Concierto;
import Entity.Escenario;
import Entity.Exposicionarte;
import Entity.Festival;
import Entity.Obrateatro;
import Entity.Persistencia;
import Entity.Presentacion;
import java.util.List;
import javax.swing.JOptionPane;
import jpaController.ConciertoJpaController;
import jpaController.EscenarioJpaController;
import jpaController.ExposicionarteJpaController;
import jpaController.FestivalJpaController;
import jpaController.ObrateatroJpaController;
import jpaController.PresentacionJpaController;
/**
 *
 * @author Jennifer
 */
public class DialogoPresentacion extends javax.swing.JDialog {
     private Presentacion presentacion;
    private PresentacionJpaController presentacionController;
    private ConciertoJpaController conciertoController;
    private ObrateatroJpaController obraTeatroController;
    private ExposicionarteJpaController exposicionArteController;
    private FestivalJpaController festivalController;
    private EscenarioJpaController escenarioController;
    /**
     * Creates new form Presentacion
     */
    public DialogoPresentacion(java.awt.Frame parent, boolean modal, Presentacion presentacion) {
        super(parent, modal);
         this.presentacion = presentacion;
        initControllers();
        initComponents();
        cargarFestivales();
        cargarEscenarios();
        configurarDialogo();
        
    }

    private void initControllers() {
        Persistencia persis = new Persistencia();
        presentacionController = new PresentacionJpaController(persis.getEmf());
        conciertoController = new ConciertoJpaController(persis.getEmf());
        obraTeatroController = new ObrateatroJpaController(persis.getEmf());
        exposicionArteController = new ExposicionarteJpaController(persis.getEmf());
        festivalController = new FestivalJpaController(persis.getEmf());
        escenarioController = new EscenarioJpaController(persis.getEmf());
    }
    
     private void cargarFestivales() {
        cbFestival.removeAllItems();
        List<Festival> festivales = festivalController.findFestivalEntities();
        for (Festival f : festivales) {
            cbFestival.addItem(f);
        }
    }
    
    private void cargarEscenarios() {
        cbEscenario.removeAllItems();
        List<Escenario> escenarios = escenarioController.findEscenarioEntities();
        for (Escenario e : escenarios) {
            cbEscenario.addItem(e);
        }
    }
    
    private void configurarDialogo() {
        if (presentacion != null) {
            txtTitulo.setText(presentacion.getTitulo());
            txtDuracion.setText(String.valueOf(presentacion.getDuracion()));
            txtCostoBase.setText(String.valueOf(presentacion.getCostoBase()));
            cbFestival.setSelectedItem(presentacion.getIdFestival());
            cbEscenario.setSelectedItem(presentacion.getIdEscenario());

            Concierto concierto = conciertoController.findConcierto(presentacion.getIdPresentacion());
            Obrateatro obra = obraTeatroController.findObrateatro(presentacion.getIdPresentacion());
            Exposicionarte exposicion = exposicionArteController.findExposicionarte(presentacion.getIdPresentacion());

            if (concierto != null) {
                cbTipoEvento.setSelectedItem("Concierto");
                txtNumArtistas.setText(String.valueOf(concierto.getNumArtistas()));
                txtGeneroMusical.setText(concierto.getGeneroMusical());
            } else if (obra != null) {
                cbTipoEvento.setSelectedItem("Obra de Teatro");
                txtNumActos.setText(String.valueOf(obra.getNumActos()));
            } else if (exposicion != null) {
                cbTipoEvento.setSelectedItem("Exposición de Arte");
                txtDiasExposicion.setText(String.valueOf(exposicion.getDiasExposicion()));
            }
        } else {
            cbTipoEvento.setSelectedIndex(0);
        }
        cambiarPanelEspecifico();
    }
    private void cambiarPanelEspecifico() {
        pnlConcierto.setVisible(false);
        pnlObraTeatro.setVisible(false);
        pnlExposicion.setVisible(false);

        String tipo = (String) cbTipoEvento.getSelectedItem();
        switch (tipo) {
            case "Concierto":
                pnlConcierto.setVisible(true);
                break;
            case "Obra de Teatro":
                pnlObraTeatro.setVisible(true);
                break;
            case "Exposición de Arte":
                pnlExposicion.setVisible(true);
                break;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtDuracion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtCostoBase = new javax.swing.JTextField();
        cbFestival = new javax.swing.JComboBox<>();
        cbEscenario = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cbTipoEvento = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pnlConcierto = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtNumArtistas = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtGeneroMusical = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        pnlObraTeatro = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtNumActos = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        pnlExposicion = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtDiasExposicion = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("PRESENTACIONES");

        jLabel2.setText("Título:");

        jLabel3.setText("Duración:");

        cbFestival.setModel(new javax.swing.DefaultComboBoxModel<Festival>());

        cbEscenario.setModel(new javax.swing.DefaultComboBoxModel<Escenario>());

        jLabel4.setText("Costo de base:");

        cbTipoEvento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Concierto", "Obra de Teatro", "Exposición de Arte" }));
        cbTipoEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoEventoActionPerformed(evt);
            }
        });

        jLabel5.setText("Festival:");

        jLabel6.setText("Escenario:");

        jLabel7.setText("Tipo de Evento:");

        pnlConcierto.setBackground(new java.awt.Color(204, 255, 204));

        jLabel8.setText("Número de artistas:");

        jLabel9.setText("Género musical:");

        jLabel11.setText("CONCIERTO");

        javax.swing.GroupLayout pnlConciertoLayout = new javax.swing.GroupLayout(pnlConcierto);
        pnlConcierto.setLayout(pnlConciertoLayout);
        pnlConciertoLayout.setHorizontalGroup(
            pnlConciertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConciertoLayout.createSequentialGroup()
                .addGroup(pnlConciertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConciertoLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(pnlConciertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(13, 13, 13)
                        .addGroup(pnlConciertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumArtistas, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGeneroMusical, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlConciertoLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel11)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        pnlConciertoLayout.setVerticalGroup(
            pnlConciertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConciertoLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(pnlConciertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumArtistas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(pnlConciertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGeneroMusical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(15, 15, 15))
        );

        pnlObraTeatro.setBackground(new java.awt.Color(204, 255, 204));

        jLabel10.setText("Número de actos:");

        jLabel12.setText("OBRA DE TEATRO");

        javax.swing.GroupLayout pnlObraTeatroLayout = new javax.swing.GroupLayout(pnlObraTeatro);
        pnlObraTeatro.setLayout(pnlObraTeatroLayout);
        pnlObraTeatroLayout.setHorizontalGroup(
            pnlObraTeatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlObraTeatroLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(txtNumActos)
                .addGap(23, 23, 23))
            .addGroup(pnlObraTeatroLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlObraTeatroLayout.setVerticalGroup(
            pnlObraTeatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlObraTeatroLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel12)
                .addGap(24, 24, 24)
                .addGroup(pnlObraTeatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtNumActos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pnlExposicion.setBackground(new java.awt.Color(204, 255, 204));

        jLabel13.setText("EXPOSICIÓN");

        jLabel14.setText("Días de Exposición:");

        javax.swing.GroupLayout pnlExposicionLayout = new javax.swing.GroupLayout(pnlExposicion);
        pnlExposicion.setLayout(pnlExposicionLayout);
        pnlExposicionLayout.setHorizontalGroup(
            pnlExposicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExposicionLayout.createSequentialGroup()
                .addGroup(pnlExposicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlExposicionLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel13))
                    .addGroup(pnlExposicionLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(txtDiasExposicion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlExposicionLayout.setVerticalGroup(
            pnlExposicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExposicionLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(pnlExposicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtDiasExposicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTitulo))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbEscenario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbTipoEvento, javax.swing.GroupLayout.Alignment.LEADING, 0, 165, Short.MAX_VALUE)
                                    .addComponent(txtCostoBase)
                                    .addComponent(cbFestival, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDuracion)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(319, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pnlObraTeatro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlConcierto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlExposicion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCostoBase, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbFestival, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbEscenario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbTipoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlConcierto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlObraTeatro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlExposicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbTipoEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoEventoActionPerformed
        cambiarPanelEspecifico();
    }//GEN-LAST:event_cbTipoEventoActionPerformed

  private void llenarDatosPresentacion() {
        presentacion.setTitulo(txtTitulo.getText());
        presentacion.setDuracion(Integer.parseInt(txtDuracion.getText()));
        presentacion.setCostoBase(Double.parseDouble(txtCostoBase.getText()));
        presentacion.setIdEscenario((Escenario) cbEscenario.getSelectedItem());
        presentacion.setIdFestival((Festival) cbFestival.getSelectedItem());
    }

private void guardarPresentacion() throws Exception {
        if (presentacion.getIdPresentacion() == null) {
            presentacionController.create(presentacion);
            presentacion = presentacionController.findPresentacion(presentacion.getIdPresentacion());
        } else {
            presentacionController.edit(presentacion);
        }
    }

 private void guardarTipoPresentacion() throws Exception {
        String tipo = (String) cbTipoEvento.getSelectedItem();
        switch (tipo) {
            case "Concierto":
                guardarConcierto();
                break;
            case "Obra de Teatro":
                guardarObraTeatro();
                break;
            case "Exposición de Arte":
                guardarExposicionArte();
                break;
        }
    }

private void guardarConcierto() throws Exception {
        Concierto concierto = conciertoController.findConcierto(presentacion.getIdPresentacion());
        if (concierto == null) {
            concierto = new Concierto();
            concierto.setIdConcierto(presentacion.getIdPresentacion());
        }
        concierto.setNumArtistas(Integer.parseInt(txtNumArtistas.getText()));
        concierto.setGeneroMusical(txtGeneroMusical.getText());

        if (conciertoController.findConcierto(concierto.getIdConcierto()) == null) {
            conciertoController.create(concierto);
        } else {
            conciertoController.edit(concierto);
        }
    }
 private void guardarObraTeatro() throws Exception {
        Obrateatro obra = obraTeatroController.findObrateatro(presentacion.getIdPresentacion());
        if (obra == null) {
            obra = new Obrateatro();
            obra.setIdObra(presentacion.getIdPresentacion());
        }
        obra.setNumActos(Integer.parseInt(txtNumActos.getText()));

        if (obraTeatroController.findObrateatro(obra.getIdObra()) == null) {
            obraTeatroController.create(obra);
        } else {
            obraTeatroController.edit(obra);
        }
    }
 private void guardarExposicionArte() throws Exception {
        Exposicionarte expo = exposicionArteController.findExposicionarte(presentacion.getIdPresentacion());
        if (expo == null) {
            expo = new Exposicionarte();
            expo.setIdExpo(presentacion.getIdPresentacion());
        }
        expo.setDiasExposicion(Integer.parseInt(txtDiasExposicion.getText()));

        if (exposicionArteController.findExposicionarte(expo.getIdExpo()) == null) {
            exposicionArteController.create(expo);
        } else {
            exposicionArteController.edit(expo);
        }
    }

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            if (presentacion == null) {
                presentacion = new Presentacion();
            }
            llenarDatosPresentacion();
            guardarPresentacion();
            guardarTipoPresentacion();
            JOptionPane.showMessageDialog(this, "Registro guardado correctamente");
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al guardar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogoPresentacion dialog = new DialogoPresentacion(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<Escenario> cbEscenario;
    private javax.swing.JComboBox<Festival> cbFestival;
    private javax.swing.JComboBox<String> cbTipoEvento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel pnlConcierto;
    private javax.swing.JPanel pnlExposicion;
    private javax.swing.JPanel pnlObraTeatro;
    private javax.swing.JTextField txtCostoBase;
    private javax.swing.JTextField txtDiasExposicion;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtGeneroMusical;
    private javax.swing.JTextField txtNumActos;
    private javax.swing.JTextField txtNumArtistas;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
