package Vistas;

import Entity.Persistencia;
import Entity.Presentacion;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jpaController.ConciertoJpaController;
import jpaController.EscenarioJpaController;
import jpaController.ExposicionarteJpaController;
import jpaController.FestivalJpaController;
import jpaController.ObrateatroJpaController;
import jpaController.PresentacionJpaController;
/**
 *
 * @author Jennifer
 */
public class Organizador extends javax.swing.JFrame {
    private Persistencia persis;
    private PresentacionJpaController presentacionController;
    private ConciertoJpaController conciertoController;
    private ObrateatroJpaController obraTeatroController;
    private ExposicionarteJpaController exposicionArteController;
    private FestivalJpaController festivalController;
    private EscenarioJpaController escenarioController;
    /**
     * Creates new form Organizador
     */
    public Organizador() {
        initComponents();
        persis = new Persistencia();
        presentacionController = new PresentacionJpaController(persis.getEmf());
        conciertoController = new ConciertoJpaController(persis.getEmf());
        obraTeatroController = new ObrateatroJpaController(persis.getEmf());
        exposicionArteController = new ExposicionarteJpaController(persis.getEmf());
        festivalController = new FestivalJpaController(persis.getEmf());
        escenarioController = new EscenarioJpaController(persis.getEmf());
        
        cargarPresentaciones();
    }

    private void cargarPresentaciones() {
        DefaultTableModel model = (DefaultTableModel) tblPresentaciones.getModel();
        model.setRowCount(0);
        
        List<Presentacion> presentaciones = presentacionController.findPresentacionEntities();
        for (Presentacion presentacion : presentaciones) {
            String tipo = "";
            double costoFinal = presentacion.getCostoBase();
            
            if (conciertoController.findConcierto(presentacion.getIdPresentacion()) != null) {
                tipo = "Concierto";
                costoFinal = presentacion.getCostoBase() * 
                    conciertoController.findConcierto(presentacion.getIdPresentacion()).getNumArtistas();
            } else if (obraTeatroController.findObrateatro(presentacion.getIdPresentacion()) != null) {
                tipo = "Obra de Teatro";
                costoFinal = presentacion.getCostoBase() * presentacion.getDuracion();
            } else if (exposicionArteController.findExposicionarte(presentacion.getIdPresentacion()) != null) {
                tipo = "Exposición de Arte";
                costoFinal = presentacion.getCostoBase() * 
                    exposicionArteController.findExposicionarte(presentacion.getIdPresentacion()).getDiasExposicion();
            }
            
            Object[] row = {
                presentacion.getIdPresentacion(),
                presentacion.getTitulo(),
                tipo,
                presentacion.getDuracion() + " min",
                "$" + presentacion.getCostoBase(),
                "$" + costoFinal,
                presentacion.getIdEscenario().getNombre(),
                presentacion.getIdFestival().getNombre(),
                presentacion.getIdEscenario().getCapacidad() + " personas"
            };
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        btnEditarPresentacion = new javax.swing.JButton();
        btnAgregarPresentacion = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPresentaciones = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menu.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setText(" BIENVENIDO ORGANIZADOR");

        btnCerrarSesion.setBackground(new java.awt.Color(102, 204, 255));
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        btnEditarPresentacion.setBackground(new java.awt.Color(102, 204, 255));
        btnEditarPresentacion.setText("EDITAR PRESENTACIÓN");
        btnEditarPresentacion.setBorder(null);
        btnEditarPresentacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarPresentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPresentacionActionPerformed(evt);
            }
        });

        btnAgregarPresentacion.setBackground(new java.awt.Color(102, 204, 255));
        btnAgregarPresentacion.setText("AGREGAR PRESENTACIÓN");
        btnAgregarPresentacion.setBorder(null);
        btnAgregarPresentacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarPresentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPresentacionActionPerformed(evt);
            }
        });

        btnActualizar.setBackground(new java.awt.Color(102, 204, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.setBorder(null);
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregarPresentacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditarPresentacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 110, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnCerrarSesion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEditarPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregarPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        tblPresentaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Título", "Tipo", "Duración", "Costo base"
            }
        ));
        jScrollPane1.setViewportView(tblPresentaciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnEditarPresentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPresentacionActionPerformed
        int filaSeleccionada = tblPresentaciones.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una presentación para editar");
            return;
        }
        
        int idPresentacion = (int) tblPresentaciones.getValueAt(filaSeleccionada, 0);
        Presentacion presentacion = presentacionController.findPresentacion(idPresentacion);

        DialogoPresentacion dialogo = new DialogoPresentacion(this, true, presentacion);
        dialogo.setVisible(true);
        cargarPresentaciones();
    }//GEN-LAST:event_btnEditarPresentacionActionPerformed

    private void btnAgregarPresentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPresentacionActionPerformed
        DialogoPresentacion dialogo = new DialogoPresentacion(this, true, null);
        dialogo.setVisible(true);
        cargarPresentaciones();
    }//GEN-LAST:event_btnAgregarPresentacionActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        cargarPresentaciones();
        JOptionPane.showMessageDialog(this, "Datos actualizados");
    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Organizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Organizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Organizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Organizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Organizador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregarPresentacion;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnEditarPresentacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel menu;
    private javax.swing.JTable tblPresentaciones;
    // End of variables declaration//GEN-END:variables
}
